#ifndef CYD_LVGL_DRV_H
#define CYD_LVGL_DRV_H

// =============================================================================
//  CYD_LVGL_DRV.H — LVGL engine interface and hardware initialisation
//
//  This module has two responsibilities:
//
//  1. HARDWARE ORCHESTRATION (init_cyd_hardware)
//     Starts all peripherals in the correct order. Order is critical:
//     the ES8311 needs the MCLK signal (generated by audio.setPinout) to
//     respond to its own I2C initialisation commands.
//     Order: I2S -> I2C/codec -> amplifier -> screen -> touch -> SD
//
//  2. LVGL ENGINE (init_cyd_lvgl)
//     - ESP32 hardware timer at 1 ms for lv_tick_inc()
//     - Graphics buffer allocation (PSRAM 320x40 or DRAM 320x10)
//     - Display driver registration (flush to ILI9341)
//     - Touch driver registration (FT6336G polling)
//     - SD filesystem driver registration (letter 'S')
//
//  AUDIO OBJECT:
//     The global object `Audio audio(true)` is defined in cyd_lvgl_drv.cpp.
//     Other modules access it via `extern Audio audio`.
//     The `true` parameter enables I2S slave mode (the ES8311 codec receives
//     the clock from the ESP32).
// =============================================================================

#include <Arduino.h>
#include <lvgl.h>


/**
 * @brief Initialises all hardware on the CYD Gold board.
 *
 *  Initialisation order (DO NOT change this order):
 *    1. audio.setPinout() — generates MCLK on GPIO4 (required for ES8311)
 *    2. setup_i2c_and_codec() — initialises ES8311 via I2C
 *    3. Amplifier (AMP_EN LOW) — enables the audio amplifier
 *    4. setup_display() — initialises ILI9341 TFT screen
 *    5. setup_touch() — initialises FT6336G touch controller
 *    6. setup_sd_card() — mounts the SD card
 *
 *  Must be called first in setup(), before init_cyd_lvgl().
 */
void init_cyd_hardware();


/**
 * @brief Initialises the LVGL engine and all its drivers.
 *
 *  Operations performed:
 *    - lv_init(): initialises the graphics engine
 *    - esp_timer (1 ms): provides the system tick to LVGL via lv_tick_inc(1)
 *      (preferred over millis() as it runs independently of loop() load)
 *    - Graphics buffer:
 *        - Attempts to allocate 320x40 pixels in PSRAM (51,200 bytes)
 *        - Falls back to 320x10 pixels in DRAM if PSRAM unavailable
 *        - Larger buffer = fewer flush calls = smoother rendering
 *    - Display driver: my_disp_flush() callback -> TFT_eSPI
 *    - Touch driver  : my_touchpad_read() callback -> FT6336G (polling)
 *    - Filesystem driver: lv_fs_sd_init() -> SD_MMC (letter 'S')
 *
 *  Must be called after init_cyd_hardware() and before ui_home_init().
 */
void init_cyd_lvgl();


/**
 * @brief Feeds the ESP32-audioI2S library decoder.
 *
 *  The ESP32-audioI2S library works by POLLING: it does not create an
 *  autonomous FreeRTOS task. Each call to audio.loop():
 *    - Reads a data chunk from the SD card (MP3/WAV/AAC/FLAC)
 *    - Decodes the chunk
 *    - Fills the I2S DMA buffer towards the ES8311 codec
 *
 *  If this function is not called frequently enough -> audio glitches.
 *  Must be in every loop() iteration, after lv_timer_handler().
 */
void loop_cyd_audio();


#endif // CYD_LVGL_DRV_H
